# Generated by Django 4.1.5 on 2023-01-07 11:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('abbr', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('year', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], default=4, max_length=5)),
                ('course', smart_selects.db_fields.ChainedManyToManyField(chained_field='school', chained_model_field='schools', horizontal=True, to='cuk.course', verbose_name='Course')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuk.school')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(choices=[('1', 1), ('2', 2)], default=1, max_length=5)),
                ('examyear', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('Main Exam', 'Main Exam'), ('Special Exam', 'Special Exam'), ('Supplimentary Exam', 'Supplimentary Exam')], max_length=100, null=True)),
                ('questions', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('courses', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='school', chained_model_field='schools', null=True, on_delete=django.db.models.deletion.CASCADE, to='cuk.course', verbose_name='courses')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuk.school')),
                ('units', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='courses', chained_model_field='course', null=True, on_delete=django.db.models.deletion.CASCADE, to='cuk.unit', verbose_name='unit')),
            ],
            options={
                'ordering': ['examyear'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='schools',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuk.school'),
        ),
    ]
