# Generated by Django 4.1.5 on 2023-01-11 08:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='questions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
